apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gtcx-staging
configMapGenerator:
  - name: markets-authority-stub-script
    files:
      - server.mjs
resources:
  - deployment.yaml
