apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: terminal-os-secrets
  namespace: terminal-os-production
  labels:
    app.kubernetes.io/part-of: gtcx
    app.kubernetes.io/component: terminal-os
    environment: production
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: terminal-os-aws-secrets
  target:
    name: terminal-os-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        key: gtcx/terminal-os/production/api-keys
