apiVersion: v1
kind: ServiceAccount
metadata:
  name: terminal-os-sa
  namespace: terminal-os-production
  labels:
    app.kubernetes.io/part-of: gtcx
    app.kubernetes.io/component: terminal-os
    environment: production
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::348389439381:role/gtcx-production-terminal-os-secrets-role
    eks.amazonaws.com/sts-regional-endpoints: 'true'
